# Generated by Django 5.2.12 on 2026-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Question in Uzbek')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Question in English')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Question in Russian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
