# Generated by Django 5.2.12 on 2026-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
