# Generated by Django 5.2.11 on 2026-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_en',
            field=models.TextField(blank=True, null=True, verbose_name='Answer in English'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Answer in Russian'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Answer in Uzbek'),
        ),
    ]
